[extend]
useDefault = true

[allowlist]
description = "ignore venv, caches, third-party vendor dirs"
paths = [
  '''\.venv/''',
  '''\.venv/.*''',
  '''__pycache__/''',
  '''.*\.pyc$''',
  '''site-packages/''',
]
